/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface LimitDialog {
      'description': string;
      'header': string;
      'image': string;
      'list': string;
      'open': boolean;
      'redirectUrl': string;
    }
  }


    interface HTMLLimitDialogElement extends StencilComponents.LimitDialog, HTMLStencilElement {}

    var HTMLLimitDialogElement: {
      prototype: HTMLLimitDialogElement;
      new (): HTMLLimitDialogElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'limit-dialog': JSXElements.LimitDialogAttributes;
    }
  }

  namespace JSXElements {

    export interface LimitDialogAttributes extends HTMLAttributes {
      'description'?: string;
      'header'?: string;
      'image'?: string;
      'list'?: string;
      'open'?: boolean;
      'redirectUrl'?: string;
    }
  }

  interface HTMLElementTagNameMap {
    'limit-dialog': HTMLLimitDialogElement
  }

  interface ElementTagNameMap {
    'limit-dialog': HTMLLimitDialogElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;